name: Build Android APK

on:
  push:
    branches: [ master ] # Sudah gue set ke master sesuai branch lo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4 # Update ke v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Update ke v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4 # Update ke v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4 # Update ke v4 (Ini penyebab error tadi)
        with:
          name: SmartKantin-V1
          path: android/app/build/outputs/apk/debug/app-debug.apk